### ISSUE TITLE
Skinning support

### ISSUE THREAD

**Issue by potch** [mozbrick/generator-brick#2]
- src directory has a skins/ subdir
- main HTML Import pulls in default skin, well, by default as well as a common stylesheet above it
- gulp build takes a 'skin' option and changes the main HTML Import to pull in the right skin.

**Comment by dotch** [comment]
subdirectory and theme compilation have been added in #9 and #11 
building brick with a 'skin' option will be tracked in https://github.com/mozbrick/brick/issues/231
